version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgrespassword}'
  graphql-engine:
    image: hasura/graphql-engine:v2.0.1
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET:?HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgrespassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-auth:3000/jwks"}'
  hasura-auth:
    image: nhost/hasura-auth:latest
    depends_on:
      - 'graphql-engine'
    ports:
      - '3000:3000'
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET:?HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
