version: '3.6'
services:
  graphql-engine:
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "${JWT_ALGORITHM}", "key": "${JWT_KEY}"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
  hasura-auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: '.env.development'
    depends_on:
      - 'mailhog'
    environment:
      NODE_ENV: development
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
    volumes:
      - .:/app
      # - /app/node_modules
    command: npm run dev-command
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
