name: Release
on: workflow_dispatch
jobs:
  test:
    uses: nhost/hasura-auth/.github/workflows/test.yml@main
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: git config
        run: |
          git config user.name "nhost"
          git config user.email "nhost@users.noreply.github.com"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: release
    uses: nhost/hasura-auth/.github/workflows/publish.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
