name: Release
on: workflow_dispatch
jobs:
  test:
    uses: nhost/hasura-auth/.github/workflows/test.yml@v1
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: git config
        run: |
          git config user.name "nhost"
          git config user.email "nhost@users.noreply.github.com"
      - run: yarn release-it --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: release
    uses: nhost/hasura-auth/.github/workflows/publish.yml@v1
