name: Release
on:
  release:
    types: [published]
jobs:
  test:
    uses: nhost/hasura-auth/.github/workflows/test.yml@main
  publish:
    needs: test
    uses: nhost/hasura-auth/.github/workflows/publish.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
